import { type Button } from "../Button/Button";

export const buttons: Button[] = [
  {
    title: 7,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 8,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 9,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: "del",
    bgColor: "bg-bg-primary",
    bgColorSecondary: "bg-bg-primary-faded",
    bgColorHover: "hover:bg-bg-primary-hover",
    textColor: "text-primary",
    isNumber: false,
  },
  {
    title: 4,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 5,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 6,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: "+",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: false,
  },
  {
    title: 1,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 2,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 3,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: "-",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: false,
  },
  {
    title: ".",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: 0,
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: true,
  },
  {
    title: "/",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: false,
  },
  {
    title: "x",
    bgColor: "bg-grey-white",
    bgColorSecondary: "bg-grey-white-faded",
    bgColorHover: "hover:bg-grey-white-hover",
    textColor: "text-bg-ternary",
    isNumber: false,
  },
  {
    title: "reset",
    bgColor: "bg-bg-primary",
    bgColorSecondary: "bg-bg-primary-faded",
    bgColorHover: "hover:bg-bg-primary-hover",
    textColor: "text-primary",
    spansTwoColumns: true,
    isNumber: false,
  },
  {
    title: "=",
    bgColor: "bg-bg-danger",
    bgColorSecondary: "bg-bg-danger-faded",
    bgColorHover: "hover:bg-bg-danger-hover",
    textColor: "text-primary",
    spansTwoColumns: true,
    isNumber: false,
  },
];
